<a href="https://colab.research.google.com/github/kanikaKanu90/notebook/blob/master/ListArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
x = ['1',2]

for i, arg in enumerate(x):
        print(f"Argument {i:6}: {arg}")
        print("Number of arguments:", len(sys.argv))

acl = ':   '+x[0]+': '  +sys.argv[1]+'  :'+ sys.argv[2]
acl

print('Argument List:', str(sys.argv)) 
print(type(x))  

y= [1,2,3]  # list
print(type(y)) 


#array
import numpy as np

a = np.ones((3,2))        # a 2D array with 3 rows, 2 columns, filled with ones
b = np.array([1,2,3])     # a 1D array initialised using a list [1,2,3]
c = np.linspace(2,3,10)  # an array with 100 points beteen (and including) 2 and 3

print(a,b,c)
print(a*1.5)  # all elements of a times 1.5
print(a.T+b)  # b added to the transpose of a




  

Argument      0: 1
Number of arguments: 3
Argument      1: 2
Number of arguments: 3
Argument List: ['/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-e03ce80b-f818-4841-8e31-1686245395d5.json']
<class 'list'>
<class 'list'>
[[1. 1.]
 [1. 1.]
 [1. 1.]] [1 2 3] [2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]
[[1.5 1.5]
 [1.5 1.5]
 [1.5 1.5]]
[[2. 3. 4.]
 [2. 3. 4.]]
