<a href="https://colab.research.google.com/github/kanikaKanu90/notebook/blob/master/ListArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
x = ['1',2]

for i, arg in enumerate(x):
        print(f"Argument {i:6}: {arg}")
        print("Number of arguments:", len(sys.argv))

acl = ':   '+x[0]+': '  +sys.argv[1]+'  :'+ sys.argv[2]
acl

print('Argument List:', str(sys.argv)) 
print(type(x))  

y= [1,2,3]  # list
print(type(y)) 


#array
import numpy as np

a = np.ones((3,2))        # a 2D array with 3 rows, 2 columns, filled with ones
b = np.array([1,2,3])     # a 1D array initialised using a list [1,2,3]
c = np.linspace(2,3,10)  # an array with 100 points beteen (and including) 2 and 3

print(a,b,c)
print(a*1.5)  # all elements of a times 1.5
print(a.T+b)  # b added to the transpose of a




  

Argument      0: 1
Number of arguments: 3
Argument      1: 2
Number of arguments: 3
Argument List: ['/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-e03ce80b-f818-4841-8e31-1686245395d5.json']
<class 'list'>
<class 'list'>
[[1. 1.]
 [1. 1.]
 [1. 1.]] [1 2 3] [2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]
[[1.5 1.5]
 [1.5 1.5]
 [1.5 1.5]]
[[2. 3. 4.]
 [2. 3. 4.]]


In [6]:
import numpy as np

text = np.random.randint(1, 1000,size=(100, 10))
text

array([[769, 308, 751, 923, 233, 126, 554, 740, 154, 384],
       [300, 534, 342, 496, 568, 817, 289, 942, 837, 642],
       [495, 557, 704, 621, 962, 795, 261, 486, 525, 533],
       [175, 698,  83, 422, 746, 938, 638, 187, 430, 902],
       [185, 369, 611, 844, 805,   9, 745, 130, 172,  92],
       [ 27,  20, 658, 584, 232, 432, 485, 345, 487, 429],
       [932, 760, 111, 449, 176, 811, 593, 945, 552, 251],
       [701, 767, 146, 658,  57, 678, 549, 557, 866, 492],
       [272, 462, 148, 840, 528, 612, 583, 117, 311, 791],
       [827,  21, 792, 108, 243,  45, 914, 109, 794, 964],
       [683, 260,  36, 761, 976, 267, 200, 782, 256, 861],
       [233, 628, 527, 195, 349, 561, 377, 196, 709, 392],
       [412, 473, 355, 414, 365, 660,  26, 985, 142, 287],
       [159,  45, 790, 798, 503,  42, 361, 268, 248, 483],
       [229, 472, 591,   1, 743, 500, 617,  31, 989, 549],
       [216, 391, 974, 534, 993, 937, 414, 403, 843,  96],
       [712,  14, 693, 154,  86, 939, 520, 973, 442, 398

In [3]:
answers = np.random.randint(0, 1,size=(50, 10))  #one-hot encoded, not integers
answers

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,

In [9]:
from keras import layers 
from keras import Input

text_input = Input(shape=(None,), dtype='int32', name='text')
print(text_input)

embedded_text = layers.Embedding(64, 1000)(text_input) #fits input:text_input into sequence of vectors of fixed size 64
embedded_text

Tensor("text_2:0", shape=(None, None), dtype=int32)


<tf.Tensor 'embedding_2/embedding_lookup/Identity_1:0' shape=(None, None, 1000) dtype=float32>