In [3]:
import numpy as np
from bokeh.sampledata.iris import flowers
flowers

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df = flowers.drop("species",axis=1)
df
arr = df.to_numpy()
arr

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
#checking the values
def rand_medoids(arr):
    ind = np.random.randint(0, len(arr)-1 ,3)
    r=[]
    for i in ind:
        r1=arr[i]
        r.append(r1)
    return r
rand = rand_medoids(arr)
rand

[array([5. , 3.3, 1.4, 0.2]),
 array([6.1, 2.8, 4. , 1.3]),
 array([6.9, 3.1, 5.4, 2.1])]

In [71]:
def pass_medoids(arr,rand_medoid):
# Use the following medoids if random medoid is set to false in the dashboard. These numbers are indices into the
# data array.
#     medoids = [24, 74, 124]
    if rand_medoid==False:
         ind = [24, 74, 124]
    elif rand_medoid==True:
          ind = np.random.randint(0, len(arr)-1 ,3)
    r=[]
    for i in ind:
        r1=arr[i]
        r.append(r1)
    return r
rand = pass_medoids(arr,False)
rand

[array([4.8, 3.4, 1.9, 0.2]),
 array([6.4, 2.9, 4.3, 1.3]),
 array([6.7, 3.3, 5.7, 2.1])]

In [7]:
#Function for measuring distance of data points from medoids 

def distance(dpArr,med_arr):
    m2=[]
    for k in dpArr:
        p=[]
        mj=[]
        if len(med_arr) == 4:
            mj.append(med_arr)  # if only one medoid is passed, converting it into array
            mj = np.asarray(mj)
            med_arr=mj
        for pm in med_arr :
#         d=arr[124]
          diff = abs(k-pm)
          dist = np.sum(diff)
          p.append(dist)
        m2.append(p)
    return m2

In [38]:
#Intializing the predefined medoids
m = [24, 74, 124]
pre_med = arr[m[0]],arr[m[1]],arr[m[2]]
pre_med
pre_medoids = np.asarray(pre_med) #array to numpy array
pre_medoids

array([[4.8, 3.4, 1.9, 0.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.7, 3.3, 5.7, 2.1]])

In [9]:
#ClusterAssignment to data points

def Cluster_assignment(k,med_arr):  # k is the array of data points , med_arr is the mediod or the set of mediods passed
    m2=[]
    F=distance(k,med_arr)
    F = np.asarray(F)
    m1=F.argmin(axis=1)
    return m1

In [10]:
mj=[]
med_arr1=pre_medoids
e=len(med_arr1)
mj.append(med_arr1)
mj = np.asarray(mj)
med_arr1=mj
g=mj.shape
# med_arr1 = np.asarray(med_arr1)
e=len(med_arr1)
e

1

In [11]:
def Cost_a(k,med_arr):
    m2=[]
#     if len([med_arr])==1:
#         med_arr=[med_arr]
    F=distance(k,med_arr)
    F = np.asarray(F)
    m2=F.min(axis=1)
    return m2

In [568]:
# def Cluster_cost(arr,meds):
    label= Cluster_assignment(arr,meds)
    dis2=[]
    dis = distance(arr,meds)
    new_med=meds
    for i in set(label):
        dpoint_cluster=arr[label==i]
        avg_dsmlrty = np.sum(Cost_a(dpoint_cluster,pre_medoids[i]))
        for dPs in dpoint_cluster:
            new_dsmlrty=np.sum(Cost_a(dpoint_cluster,dPs))
            if new_dsmlrty < avg_dsmlrty:
                avg_dsmlrty =  new_dsmlrty
                new_med[i]= dPs  
                print(i)
        print(avg_dsmlrty)
        return new_med ,  avg_dsmlrty

In [118]:
def Cluster_cost(arr,meds):
    label= Cluster_assignment(arr,meds)
    dis2=[]
    dis = distance(arr,meds)
    new_med=meds
    avg_dsmlrty=[]*3
    print(set(label))
    for i in set(label):
        dpoint_cluster=arr[label==i]
        avg_dsmlrty.append(np.sum(Cost_a(dpoint_cluster,pre_medoids[i])))
        for dPs in dpoint_cluster:
            new_dsmlrty=np.sum(Cost_a(dpoint_cluster,dPs))
            if new_dsmlrty < avg_dsmlrty[i]:
                avg_dsmlrty[i] =  new_dsmlrty
                new_med[i]= dPs
        cost=np.sum(avg_dsmlrty)
    return new_med ,  cost

In [85]:
label= Cluster_assignment(arr,pre_medoids)
dis2=[]
dis = distance(arr,rand)
avg_dsmlrty=[0,0,0]
new_med=rand
for i in set(label):
    dpoint_cluster=arr[label==i]
    print(i)

0
1
2


In [138]:
def convergence(oldMed,newMed):
    return set([tuple(x) for x in oldMed])==set([tuple(x) for x in newMed])

In [137]:
rand=pass_medoids(arr,True)
print(rand)
# f,h =Cluster_cost(arr,pre_medoids)
i,j=Cluster_cost(arr,rand)
print ('medoids: ' , i)
print('cost is : ' , j)

[array([6.4, 2.8, 5.6, 2.1]), array([7.1, 3. , 5.9, 2.1]), array([6.1, 2.8, 4.7, 1.2])]
{0, 1, 2}
medoids:  [array([6.4, 2.8, 5.6, 2.1]), array([7.1, 3. , 5.9, 2.1]), array([5.6, 2.9, 3.6, 1.3])]
cost is :  360.89999999999986


In [420]:
# def k_medoids(arr,pre_or_rand):
    # number of clusters:
    k = 3
    # Use the following medoids if random medoid is set to false in the dashboard. These numbers are indices into the
    # data array.
#     medoids = [24, 74, 124]
    med=pass_medoids(arr,pre_or_rand)
    # f,h =Cluster_cost(arr,pre_medoids)
    medoids,cost=Cluster_cost(arr,med)
    print ('medoids: ' , medoids)
    print('cost is : ' , cost)
    converged = False
        labels = np.zeros(len(Array))
        i = 1
        while (not converged):
              old_medoids = medoids.copy()
              D = distance(arr, medoids) 
              labels = Cluster_assignment(Array,medoids)
              medoids,cost =Cluster_cost(arr,med)
              converged = convergence(old_medoids, medoids)
              i += 1
              return (medoids,labels)

In [219]:
def k_medoids(arr,pre_or_rand):
    # number of clusters:
    k = 3
    # Use the following medoids if random medoid is set to false in the dashboard. These numbers are indices into the
    # data array.
#     medoids = [24, 74, 124]
    med=pass_medoids(arr,pre_or_rand)
    # f,h =Cluster_cost(arr,pre_medoids)
    medoids,cost=Cluster_cost(arr,med)
#     print ('medoids: ' , medoids)
#     print('cost is : ' , cost)
    converged = False
    i = 1
    while (not converged):
           old_medoids = medoids.copy()
           medoids,cost = Cluster_cost(arr,med)
           converged = convergence(old_medoids, medoids)
           i += 1
    return medoids,cost

In [220]:
medoids,cost = k_medoids(arr,True)
print ('medoids: ' , medoids)
print('cost is : ' , cost)

{0, 1, 2}
{0, 1, 2}
{0, 1, 2}
medoids:  [array([6.8, 3. , 5.5, 2.1]), array([5. , 3.4, 1.5, 0.2]), array([5.7, 2.8, 4.5, 1.3])]
cost is :  162.5
